services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    #restart: always
    environment:
      - ISC_CPF_MERGE_FILE=/home/irisowner/dev/merge.cpf
    #env_file:
    #  - .env
    ports:
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
    depends_on:
      - httpbin

  # A simple HTTP service used for integration testing of the FastHTTP class
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "9292:80"
